import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import HeaderTop from "@/components/headertop";
import Header from "@/components/header";
import NavBar from "@/components/navbar";
import Hero from "@/components/hero";
import NewProducts from "@/components/newproducts";
import React, { useState } from "react";
import CartItem from "@/components/cartitem";  
import Cart from "@/components/cart";




const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HeaderTop/>
        <Header/>
        <NavBar/>
        <Hero/>
        <NewProducts/>
        <Cart/>
        <CartItem/>
       
        {children}
      </body>
    </html>
  );

}
